services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    working_dir: /src/GameApi
    command: dotnet watch run --non-interactive
    ports:
      - "5135:5135"
    environment:
      DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER: "1"
    volumes:
      - ..:/src

  frontend:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    working_dir: /src/GameFrontend
    command: dotnet watch run --non-interactive
    ports:
      - "3000:3000"
    environment:
      DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER: "1"
    volumes:
      - ..:/src
